
import AuthProvider from '@/components/auth-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ReduxProvider from '@/components/redux-provider'
import ConfettiProvider from '@/providers/confetti-provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
   <ReduxProvider>
    <html lang="en">
      <body className={inter.className}>
      <ConfettiProvider></ConfettiProvider>
      {children}
     
      </body>
    </html>
    </ReduxProvider>
     </AuthProvider>
  )
}
